In [ ]:
import numpy as np # importin numpy library

create

In [27]:
x1 = np.array([1, 2, 3, 4, 5]) # creating an array
print(x1) # printing the array
print(type(x1)) # printing the type of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [28]:
x2 = np.array([[1, 2, 3], [4, 5, 6]]) # creating a 2D array

print(x2) # printing the 2D array
print(type(x2)) # printing the type of the 2D array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [29]:
x3 = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
]) # creating a 3D array
print(x3) # printing the 3D array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


methods to create matrix

1D 
arange() - start, stop, step
linspace() - start, stop, numOfElements

nD
random.randit() - low, high, size 

In [30]:
a = np.arange(10, 51, 5) # creating an array with numbers from 10 to 51 with a step of 5
print(a) # printing the array
print(a.shape) # printing the shape of the array

[10 15 20 25 30 35 40 45 50]
(9,)


In [31]:
b = np.linspace(10, 20, 100) # creating an array with 100 numbers from 10 to 20 
print(b) # printing the array

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [32]:
c = np.random.randint(-100, 100, (5, 5)) # creating a 5x5 array with random numbers from 10 to 20 
print(c) # printing the array

[[ -86  -27   14   69  -82]
 [-100   25  -78   78   -4]
 [  41  -46  -20  -94   90]
 [  43  -72  -89  -79   36]
 [   1   -7   55  -79  -23]]


In [35]:
m1 = np.array([[2, 4, 6], [1, 3, 5]]) 

m2 = np.array([[1,2], [5, 1], [3,2]])

print(m1, m2, sep='\n') # printing the arrays
print(m1@m2) # printing the result of the matrix multiplication

[[2 4 6]
 [1 3 5]]
[[1 2]
 [5 1]
 [3 2]]
[[40 20]
 [31 15]]
