# 29/02/2024

In [ ]:
import numpy as np # importin numpy library

create

In [ ]:
x1 = np.array([1, 2, 3, 4, 5]) # creating an array
print(x1) # printing the array
print(type(x1)) # printing the type of the array

In [ ]:
x2 = np.array([[1, 2, 3], [4, 5, 6]]) # creating a 2D array

print(x2) # printing the 2D array
print(type(x2)) # printing the type of the 2D array

In [ ]:
x3 = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
]) # creating a 3D array
print(x3) # printing the 3D array

methods to create matrix

1D 
arange() - start, stop, step
linspace() - start, stop, numOfElements

nD
random.randit() - low, high, size 

In [ ]:
a = np.arange(10, 51, 5) # creating an array with numbers from 10 to 51 with a step of 5
print(a) # printing the array
print(a.shape) # printing the shape of the array

In [ ]:
b = np.linspace(10, 20, 100) # creating an array with 100 numbers from 10 to 20 
print(b) # printing the array

In [ ]:
c = np.random.randint(-100, 100, (5, 5)) # creating a 5x5 array with random numbers from 10 to 20 
print(c) # printing the array

In [ ]:
m1 = np.array([[2, 4, 6], [1, 3, 5]]) 

m2 = np.array([[1,2], [5, 1], [3,2]])

print(m1, m2, sep='\n') # printing the arrays
print(m1@m2) # printing the result of the matrix multiplication

# 1/03/2024

In [ ]:

print(m1)
print(f'size => {m1.size}')
print(f'shape => {m1.shape}')
print(f'dimension => {m1.ndim}')
print(f'data type => {m1.dtype}')


In [ ]:
n = np.random.randint(10, 99, (4, 5))
print(n)
print(n.reshape(5, 4))
#print(n.reshape(20, 1))
#print(n.reshape(1, 20))


In [ ]:
print(n.flatten()) # converting the 2D array to 1D array

In [ ]:
y = np.random.randint(10,99, (5, 2))
print(y)

In [ ]:
print(y.T) # transposing the array

maths and stats

In [ ]:
a = np.array([[2,4], [1,3]])
b = np.array([[1,2], [5,1]])

#addition
print(a+b)

#subtraction
print(a-b)

#multiplication
print(a*b)

#division
print(a/b)

#dot product
print(a@b) # or print(np.dot(a, b)) 

In [ ]:
print(y)
print(y.sum()) # sum of all elements in the array
print(y.sum(axis=0)) # sum of each column
print(y.sum(axis=1)) # sum of each row

#min and max
print(y.min(), y.max()) # minimum value in the array

#argmin and argmax 
print(y.argmin(), y.argmax()) # index of the minimum value in the array 



sclicing
 - 1D
 ```python
 x[start:stop:step]
 
- 2D
```python
x[rowstart:rowstop:rowstep, colstart:colstop:colstep]

In [ ]:
x = np.random.randint(10, 100, (10, 10))
print(x)

In [44]:
print(x[0,0]) # first element
print(x[-1,-1]) # last element
print(x[0]) # first row
print(x[-1]) # last row
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:5, 1]) # first 5 elements of the second column
print(x[-5:, 3]) # last 5 elements of the 4th column
print(x[:, :3]) # first 3 columns
print(x[:, -3:]) # last 3 columns

29
64
[29 12 63 10 50 23 63 87 88 30]
[46 76 20 76 12 78 96 69 46 64]
[29 86 77 67 97 36 58 62 57 46]
[30 88 58 41 36 11 73 14 71 64]
[12 44 69 83 91]
[83 13 39 43 76]
[[29 12 63]
 [86 44 82]
 [77 69 35]
 [67 83 18]
 [97 91 81]
 [36 96 27]
 [58 12 15]
 [62 25 41]
 [57 67 35]
 [46 76 20]]
[[87 88 30]
 [28 90 88]
 [31 89 58]
 [38 32 41]
 [10 26 36]
 [92 87 11]
 [80 23 73]
 [86 29 14]
 [56 56 71]
 [69 46 64]]


#find index of any item in matrix

In [45]:
print(np.where(x == 10)) # indices of the elements that are equal to 10
print(np.count_nonzero(x == 10)) # number of elements that are equal to 10

(array([0, 4], dtype=int64), array([3, 7], dtype=int64))
2
